### ISSUE TITLE
-x doesn't work

### ISSUE THREAD

**Issue by edbryant356** [nprint/nprintML#65] opened 2021-06-23 16:47 UTC
I've tried using "nml -4 --pcap-dir pcaps -L labels.txt -a pcap -x "ipv4_src*" -R" but in the feature.csv file generated by nprint the source IP related features are still there. Seems that -x doesn't work. I would like to extract the source and destination ips as well as the packet length, but if I understand it correctly, in nprint you can only use "-x" to remove header fields instead of specifying fields to keep, how would I do that?

**Comment by jesteria** [comment] 2021-06-23 17:42
Hey, thanks for the report. Since nprintML is just passing this flag along to nPrint, it "should" work without difficulty; but, we can see what might be happening.

---

This problem run will have generated a file `meta.toml` in the nprintML output directory – I think I see what's going on, but if you like you might review and/or share that file, or at least its `nprint.cmd` field.

And, then, you might also test the issue on a single PCAP file in your target directory:

    nprint -4 -x "ipv4_src*" … FILE

---

That said, this doesn't *appear* to be a bug. Rather, nprintML and nPrint describe this option as follows:

     -x STRING, --nprint-filter STRING, --nprint_filter STRING
                        regex to filter bits out of nPrint output (for details see --help-nprint-filter)

That is, this option expects a regular expression – not a glob.

In my own testing, I can reproduce what you saw, using the value `ipv4_src*`. However, I believe that this is because evaluating this argument as a regular expression renders it null. Reproducing it as below appears to resolve the issue entirely (in both nprintML and in nPrint alone):

    nml -4 -R -a pcap -L test/data/dir-pcap/labels-abridged.txt --pcap-dir test/data/dir-pcap/pcaps/ -x "ipv4_src.*"

(Note the insertion of a period into the value.)

---

I'm going to close this out, but do feel free to let me know if this resolves your issue, or not, *etc*.

**Closed by jesteria** 2021-06-23 17:42 UTC
